# Generated by Django 6.0.2 on 2026-02-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todoitem_due_date_todoitem_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='category',
            field=models.CharField(choices=[('WORK', 'Work'), ('PERSONAL', 'Personal'), ('SHOPPING', 'Shopping'), ('HEALTH', 'Health'), ('LEARNING', 'Learning'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
